name: Publish to NPM
on:
  release:
    types: [created,published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: pnpm install
      - name: Publish package on NPM 📦
        run: pnpm build:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
